---
default:
  cores: 19
  debug: true
  server: "localhost:5555"

additionalClustering:
  dataDir: "../data/RNAseq"
  countFile: "counts.csv"
  countPath: ${additionalClustering.dataDir}/${additionalClustering.countFile}
  labelsDir: "${additionalClustering.dataDir}/clustering pipeline after m3c"
  labelsFile: "labels from bisecting kmeans.csv"
  labelsPath: ${additionalClustering.labelsDir}/${additionalClustering.labelsFile}

randomData:
  nSamples: 500
  rng:
    - 0
    - 100
  randomDataDir: "../data/RNAseq"
  randomDataFile: "randomData.csv"
  randomDataPath: "${randomData.randomDataDir}/${randomData.randomDataFile}"
  pcaFile: "pca on no structured data.csv"
  pcaPath: "${randomData.randomDataDir}/${randomData.pcaFile}"
