---
default:
  cores: 19
  debug: true
  server: "localhost:5555"

additionalClustering:
  dataDir: "../data/intermediate/exp1/RNAseq"
  countFile: "counts.csv"
  countPath: ${additionalClustering.dataDir}/${additionalClustering.countFile}
