---
default:
  cores: 19
  debug: true
  server: "localhost:5555"

additionalClustering:
  dataDir: "../data/RNAseq"
  countFile: "counts.csv"
  countPath: ${additionalClustering.dataDir}/${additionalClustering.countFile}
  labelsDir: "${additionalClustering.dataDir}/clustering pipeline after m3c"
  labelsFile: "labels from bisecting kmeans.csv"
  labelsPath: ${additionalClustering.labelsDir}/${additionalClustering.labelsFile}
