---
default:
  cores: 19
  debug: true
  server: "localhost:5555"
  parent: !expr dirname(dirname(getwd()))
  udfPath: "../../scripts/functions.r"
  pkg: !expr c("tidyverse", "yaml", "fst", "openxlsx", "splitstackshape", "rstatix",
        "lme4", "cvms", "groupdata2", "mice", "emmeans", "rsq", "ordinal", "rcompanion")
  
metadata:
  studyDir: !expr file.path("../../", "data", "study_data")
  m3cLabelsPath: !expr file.path("../../", "exp1/data/RNAseq/clustering/m3c pd labels.xlsx")
  rnaMetaPath: !expr file.path("../../", "metadata/our RNA seq metadata updated with analytic cohort info.rds")
  analyticMetaPath: !expr file.path("../../", "metadata/our study cohort.rds")
  codebook: !expr file.path("../../", "metadata/Codebook of columns.xlsx")
  
biospecimen:
  cr: !expr file.path("../../", "data/study_data/Biospecimen", "Current_Biospecimen_Analysis_Results.csv")
  
medicalHistory:
  path: "../../data/study_data/Medical_History"
  
motorAssessment:
  path: "../../data/study_data/Motor_Assessments"
  
nonMotorAssessment:
  path: "../../data/study_data/Non-motor_Assessments"
  
subjectCharacteristics:
  scdir: "../../data/study_data/Subject_Characteristics"
  demodir: "../../data/study_data/Subject_Characteristics/demographics"
  geneticdir: "../../data/study_data/Subject_Characteristics/genetic status"
  scexportdir: "../data/intermediate/"
  scexportfile: "subject_characteristics res.rds"
  
excluded_first_iter: !expr c("Curated_Data_Cuts", "DaTSCAN", "Follow_Up_persons_w_Neurologic_Disease", "PPMI_Online", "Verily_Study_Watch")
variables_to_exclude: !expr c("PAG_NAME", "INFODT", "REC_ID", "ORIG_ENTRY", "LAST_UPDATE")
