---
title: "Univariate filtering summary"
author: "Andrea Termine"
date: '2022-06-20'
output:  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r config}
# plant a seed
set.seed(12345)

# Path to config
config = yaml::read_yaml(file = "../config/config r.yaml", eval.expr=TRUE)

# Paths
udf.path        = file.path(config$exp$parent, config$file_05$udf_dir)
rna.meta.path   = file.path(config$exp$parent, config$file_05$rna_meta_dir)
```


```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
# Import custom functions
source(file.path(udf.path, config$file_05$udf_name))

## Required Packages
pkg = c("tidyverse", "yaml", "fst",
        "FactoMineR", "factoextra", "mclust",
        "fpc", "dbscan", "clusterCrit", "openxlsx",
        "patchwork", "seriation", "M3C")

## Now load or install & load all // Cran version
load_packages(pkgs = pkg)
# cat("Libraries Imported")
rm(pkg,p)
```

## Generate Random data and test them

We are building a simulated negative control were k = 1 to demonstrate the difference with our PD cohort.

```{r Generate random data, eval=FALSE, include=FALSE}
# Generate Random data ----
nc = MMDai::GenerateData(n = 500,                 # samples
                         p = 1000,                # variables
                         d = rep(10, 1000),       # categories for each variables
                         k = 1) %>%               # latent classes
        as.data.frame()

# Build distance matrix and test IVAT ----
nc_dist = dist(scale(nc) %>% as.data.frame(),
            method  = config$clustering$IVAT_method)

ivat_nc_plot = ggiVAT(nc_dist)
ivat_nc_plot

ggsave(filename = file.path("../", config$results_presenting$ivat_nc_plot),
       plot     = ivat_nc_plot,
       units    = "cm",
       dpi      = 300,
       width    = 26,
       height   = 24, 
       device   = "png")

# Perform a PCA and inspect it ----
nc_PCA = PCA(nc,
             scale.unit = T, 
             graph      = F)

fviz_pca_ind(X     = nc_PCA,
             label = "none")

# Perform M3C ----
m3c_nc = M3C(mydata        = nc %>% scale %>% t() %>% as.data.frame(),
             cores         = config$default$cores,
             method        = 1,
             iters         = 25,
             maxK          = 10,
             pItem         = 0.8,
             des           = NULL,
             ref_method    = "chol",
             repsref       = 100,
             repsreal      = 100,
             clusteralg    = "km",
             pacx1         = 0.1,
             pacx2         = 0.9,
             seed          = 12345,
             objective     = "entropy",
             removeplots   = FALSE,
             silent        = FALSE,
             fsize         = 18,
             lambdadefault = 0.1,
             tunelambda    = TRUE,
             lseq          = seq(0.02, 0.1, by ,0.02),
             lthick        = 2,
             dotsize       = 3)

save(nc, m3c_nc, nc_PCA, file = file.path("../", config$results_presenting$nc_objects) )


# Build distance matrix and test IVAT ----
pd_dist = dist(pd_counts,
               method  = config$clustering$IVAT_method)

ivat_pd_plot = ggiVAT(pd_dist)
ivat_pd_plot
```


## Import

We need some files to import:

1) Random data (negative control)
   - RandomData.csv                [V]
   - pca on no structured data.csv [V]
   - IVAT                          [V]
   - M3C                           [V]

2) PD
 - distance matrices [V]
 - plot ivat         [V]
 - entropy pca.rds   [V]
 - m3c pd labels     [V]
 - counts            [V]
 - m3c object PD     [V]

```{r import}
# Random ----
load( file.path("../", config$results_presenting$nc_objects))

# PD ----
# PD counts
pd_counts = read.fst(file.path("../", config$results_presenting$count_pd))

# IVAT
load(file = file.path("../", config$results_presenting$ivat_pd))
rm(count.ivat.plot.list) # This file is corrupted

# PCA on PD (?)
entropyPCA = readRDS(file.path("../", config$results_presenting$entropy_pca))

# m3c PD labels
m3cLabels = read.xlsx(file.path("../", config$results_presenting$m3c_PD_labels))

# m3c PD object
m3c_pd_object = readRDS(file.path("../", config$results_presenting$m3c_object))

# summary of internal validation metrics
int_metrics_summary = read.xlsx(file.path(config$clustering_after_m3c$intMetricsDir, config$clustering_after_m3c$intMetricsFile))
```

## Prep plotting

```{r nc plots}
nc_entropy = 
m3c_nc$scores %>% 
        ggplot() +
        aes(x = K,
            y = ENTROPY_REAL) +
        geom_point(size = 1) +
        geom_line() +
        scale_x_continuous(breaks = seq(from = 2, to = 10, by = 1), limits = c(2,10)) +
        labs(x = "K",
             y = "Entropy",
             subtitle = "2B")

nc_pvalue = 
m3c_nc$scores %>% 
        ggplot() +
        aes(x = K,
            y = P_SCORE) +
        geom_point(size = 1) +
        scale_x_continuous(breaks = seq(from = 2, to = 10, by = 1), limits = c(2,10)) +
        geom_hline(yintercept = -log10(0.05), linetype = "dashed", size = 0.5) +
        labs(x = "K",
             y = bquote(-log[10]~p),
             subtitle = "2D")

nc_rcsi =
m3c_nc$scores %>% 
        ggplot() +
        aes(x = K,
            y = RCSI) +
        geom_point(size = 1) +
        geom_line() +
        geom_errorbar(aes(ymin = RCSI - RCSI_SE, ymax = RCSI + RCSI_SE), width = 0.2, position= position_dodge(.9), size = 0.1) +
        scale_x_continuous(breaks = seq(from = 2, to = 10, by = 1)) +
        labs(subtitle = "2C")

nc_pca_ind = 
nc_PCA$ind$coord %>%
        as.data.frame() %>% 
        ggplot() +
        aes(x = Dim.1,
            y = Dim.2) +
        geom_point(size = 1) +
        geom_hline(yintercept = 0, linetype = "dashed", size = 0.5) +
        geom_vline(xintercept = 0, linetype = "dashed", size = 0.5) +
        labs(x = "Dim.1 (0.6%)",
             y = "Dim.2 (0.6%)",
             title = "Negative Control (K = 1)",
             subtitle = "2A")

ivat_nc_prova = ivat_nc_plot + theme(legend.position = "null") + labs(y = "IVAT", subtitle = "2E")
nc_panel = nc_pca_ind | (nc_entropy + nc_rcsi + nc_pvalue + ivat_nc_prova) 



ggsave(filename = file.path("../data/RNAseq/nc_panel.png"),
       plot     = nc_panel,
       units    = "cm",
       dpi      = 300,
       width    = 20,
       height   = 10, 
       device   = "png")
```

```{r PD}
pd_entropy = 
        m3c_pd_object$scores %>% 
        mutate(is.significant = ifelse(K == 2, "Best K", "no")) %>%
        ggplot() +
        aes(x      = K,
            y      = ENTROPY_REAL,
            colour = is.significant) +
        geom_line(group = 1, color = "black") +
        geom_point(size = 1) +
        scale_x_continuous(breaks = seq(from = 2, to = 10, by = 1)) +
        scale_colour_manual(values = c("green3", NA), limits = "Best K",  guide = NULL) +
        annotate("rect", xmin = 1.6, xmax = 2.4, ymin = 800, ymax = 1800, alpha = .1, fill = "blue") +
        labs(x = "K",
             y = "Entropy",
             colour = "",
             subtitle = "1B") +
        theme_gray()

pd_pvalue = 
m3c_pd_object$scores %>% 
        mutate(is.significant = ifelse(K == 2, "Best K", "no")) %>% 
        ggplot() +
        aes(x      = K,
            y      = P_SCORE,
            colour = is.significant) +
        geom_point(size = 1) +
        geom_hline(yintercept = -log10(0.05), linetype = "dashed", size = 0.5) +
        annotate("rect", xmin = 1.6, xmax = 2.4, ymin = 1.2, ymax = 1.6, alpha = .1, fill = "blue") +
        annotate("text", x = 2, y = 1.8, label = "", size = 4) +
        scale_colour_manual(values = c("green3", NA), limits = "Best K", guide = NULL) +
        scale_x_continuous(breaks = seq(from = 2, to = 10, by = 1)) +
        labs(x = "K",
             y = bquote(-log[10]~p),
             colour = "",
             subtitle = "1D") +
        theme_gray()
                
pd_rcsi = 
        m3c_pd_object$scores %>% 
        mutate(is.significant = ifelse(K == 2, "Best K", "no")) %>%
        ggplot() +
        aes(x = K,
            y = RCSI,
            colour = is.significant) +
        geom_line(color = "black") + 
        geom_point(size = 1) +
        geom_errorbar(aes(ymin = RCSI - RCSI_SE, ymax = RCSI + RCSI_SE), width = 0.2, position= position_dodge(.9), size = 0.1) +
        scale_x_continuous(breaks = seq(from = 2, to = 10, by = 1)) +
        scale_colour_manual(values = c("green3", NA), limits = "Best K", guide = NULL) +
        annotate("rect", xmin = 1.6, xmax = 2.4, ymin = 1.7, ymax = 2, alpha = .1, fill = "blue") +
        labs(colour = "",
             subtitle = "1C") +
        theme_gray()

pd_pca_ind = 
        entropyPCA$ind$coord %>%
        as.data.frame() %>% 
        mutate(label  = as.factor(as.character(m3cLabels$label)),
               label2 = ifelse(label == 1, "PDC1", "PDC2")) %>% 
        ggplot() +
        aes(x = Dim.1,
            y = Dim.2,
            color = label2) +
        geom_point(size = 1) +
        geom_hline(yintercept = 0, linetype = "dashed", size = 0.5) +
        geom_vline(xintercept = 0, linetype = "dashed", size = 0.5) +
        labs(x = "Dim.1 (59.3%)",
             y = "Dim.2 (1.2%)",
             color = "",
             subtitle = "1A",
             title = expression(paste("PD Cohort (", K != 1 , ")"))) +
        theme_gray() +
        theme(legend.position = c(0.8, 0.12),
        legend.background     = element_blank())


ivat_pd_prova = ivat_pd_plot + theme(legend.position = "null",  
                                     panel.background=element_blank(), 
                                     panel.grid.major=element_blank(), 
                                     panel.grid.minor=element_blank()) +
        labs(y = "IVAT", subtitle = "1E")


pd_panel = pd_pca_ind | ( pd_entropy + pd_rcsi + pd_pvalue + ivat_pd_prova) + plot_layout()


ggsave(filename = file.path("../data/RNAseq/pd_panel.png"),
       plot     = pd_panel,
       units    = "cm",
       dpi      = 300,
       width    = 20,
       height   = 10, 
       device   = "png")
```

```{r Export combined panels}
combined_panels = pd_panel / nc_panel + plot_layout(tag_level = "keep")

ggsave(filename = file.path("../data/RNAseq/combined_panel.png"),
       plot     = combined_panels,
       units    = "cm",
       dpi      = 300,
       width    = 20,
       height   = 20, 
       device   = "png")
```

```{r}
int_metrics_plot = 
int_metrics_summary %>%
        filter(method %in% c("c_index","calinski_harabasz","dunn", "silhouette")) %>% 
        distinct() %>% 
        mutate(type   = ifelse(type == "M3C", "Selected Algorithm", NA_character_),
               method = case_when(method == "M3C"~  "Selected Algorithm",
                                  method == "calinski_harabasz" ~ "Calinski-Harabasz",
                                  method == "dunn" ~ "Dunn",
                                  method == "c_index" ~ "C index",
                                  method == "silhouette" ~ "Silhouette",
                                  TRUE ~ "HELP")) %>% 
        ggplot() +
        aes(y    = value,
            fill = type) +
        geom_histogram(bins = 45) +
        scale_fill_manual(values = c("green3", NA), limits = "Selected Algorithm") +
        facet_wrap(~ method, ncol = 2, scales = "free") +
       theme(legend.position = "bottom") +
        coord_flip() +
        labs(x = "n° of algorithms",
             y = "Performance",
             fill = NULL)

ggsave(filename = file.path("../data/RNAseq/int_metrics plot.png"),
       plot     = int_metrics_plot,
       units    = "cm",
       dpi      = 300,
       width    = 14,
       height   = 16, 
       device   = "png")

 
# m3c percentile on siljouette      
int_metrics_summary %>% 
        filter(method == "silhouette") %>% distinct() %>% 
        mutate(rank = percent_rank(value)) %>% 
        filter(type == "M3C")


# m3c score on silhouette
int_metrics_summary$value[int_metrics_summary$type == "M3C" & int_metrics_summary$method == "silhouette"] %>% unique()

# n observations that score equal to m3c
int_metrics_summary %>% 
        filter(method == "silhouette") %>% 
        distinct() %>% 
        group_by(value) %>% 
        tally() %>% arrange(-n)

# % percentage of observations that score equal to M3C
round((40/165)*100,2)

m3cLabels$label %>% table() %>% addmargins()
```


