---
default:
  cores: 19
  debug: true
  server: "localhost:5555"
  
metabuild:
  parent: !expr dirname(dirname(getwd()))
  
exp1:
  parent: !expr dirname(dirname(getwd()))
  datapath: "data/genetic_data/RNA_seq/counts"
  rna.meta.path: "data/intermediate/metadata"
  metadata_rna: "our RNA seq metadata updated with analytic cohort info.rds"
  lcf.out: "data/intermediate/exp1/RNAseq/lcf"
  udf.path: "r/scripts"
  fit_types: !expr c("parametric", "local", "mean")
  group_names: !expr c("hc_lcf", "pd_lcf")
  vst.count.list.names: !expr c("hc_lcf_vst", "pd_lcf_vst")
  vst.out: "data/intermediate/exp1/RNAseq/vst"
  vst.ff.out: "data/intermediate/exp1/RNAseq/vst_ff"
  vst.ff.stats: "data/intermediate/exp1/RNAseq/vst_ff/ff stats"
  featurefilter: "MAD"

clustering:
  prep_methods: !expr c("lcf", "lcf_vst", "lcf_vst_cs", "lcf_vst_ff", "lcf_vst_ff_cs")
  random_df: "data/intermediate/exp1/RNAseq/clustering"
  ctend.out: "data/intermediate/exp1/RNAseq/clustering/clustering tendency results"
  hopkins.out: "hopkins"
  VAT_out: "vat"
  VAT_method: "euclidean"
  IVAT_method: "euclidean"
  IVAT_out: "ivat"
  diss_out: "dissimilarity plots"
  IVAT_dissimilarity_method: "OLO_single"
  corr.out: "correlation"
  correlation_methods: !expr c("pearson", "spearman")
  M3C_alg: !expr c("pam", "km", "spectral", "hc")
  M3C_obj_fun: !expr c("entropy", "PAC")
  M3C_ref_meth: !expr c("reverse-pca", "chol")
  M3C.out: "m3c/method1"
